// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

/**
 * Protobuf type {@code omega.ChannelMessage}
 */
public final class ChannelMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omega.ChannelMessage)
    ChannelMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelMessage.newBuilder() to construct.
  private ChannelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelMessage() {
    channelId_ = "";
    fromSession_ = "";
    message_ = "";
    subject_ = "";
    subjectName_ = "";
    roleIndicator_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChannelMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            channelId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            fromSession_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 40: {

            offset_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            subject_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            subjectName_ = s;
            break;
          }
          case 64: {

            sequential_ = input.readBool();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            roleIndicator_ = rawValue;
            break;
          }
          case 82: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.kklab.vd.kumoi.proto.Skill.Builder subBuilder = null;
            if (skill_ != null) {
              subBuilder = skill_.toBuilder();
            }
            skill_ = input.readMessage(com.kklab.vd.kumoi.proto.Skill.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(skill_);
              skill_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_ChannelMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_ChannelMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kklab.vd.kumoi.proto.ChannelMessage.class, com.kklab.vd.kumoi.proto.ChannelMessage.Builder.class);
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object channelId_;
  /**
   * <code>string channel_id = 2[json_name = "ch"];</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelId_ = s;
      return s;
    }
  }
  /**
   * <code>string channel_id = 2[json_name = "ch"];</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_SESSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object fromSession_;
  /**
   * <code>string from_session = 3[json_name = "fs"];</code>
   * @return The fromSession.
   */
  @java.lang.Override
  public java.lang.String getFromSession() {
    java.lang.Object ref = fromSession_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromSession_ = s;
      return s;
    }
  }
  /**
   * <code>string from_session = 3[json_name = "fs"];</code>
   * @return The bytes for fromSession.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromSessionBytes() {
    java.lang.Object ref = fromSession_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromSession_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFSET_FIELD_NUMBER = 5;
  private long offset_;
  /**
   * <code>int64 offset = 5[json_name = "o", jstype = JS_STRING];</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int SUBJECT_FIELD_NUMBER = 6;
  private volatile java.lang.Object subject_;
  /**
   * <code>string subject = 6[json_name = "sub"];</code>
   * @return The subject.
   */
  @java.lang.Override
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   * <code>string subject = 6[json_name = "sub"];</code>
   * @return The bytes for subject.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object subjectName_;
  /**
   * <code>string subject_name = 7[json_name = "sn"];</code>
   * @return The subjectName.
   */
  @java.lang.Override
  public java.lang.String getSubjectName() {
    java.lang.Object ref = subjectName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectName_ = s;
      return s;
    }
  }
  /**
   * <code>string subject_name = 7[json_name = "sn"];</code>
   * @return The bytes for subjectName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectNameBytes() {
    java.lang.Object ref = subjectName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQUENTIAL_FIELD_NUMBER = 8;
  private boolean sequential_;
  /**
   * <code>bool sequential = 8[json_name = "se"];</code>
   * @return The sequential.
   */
  @java.lang.Override
  public boolean getSequential() {
    return sequential_;
  }

  public static final int ROLEINDICATOR_FIELD_NUMBER = 9;
  private int roleIndicator_;
  /**
   * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
   * @return The enum numeric value on the wire for roleIndicator.
   */
  @java.lang.Override public int getRoleIndicatorValue() {
    return roleIndicator_;
  }
  /**
   * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
   * @return The roleIndicator.
   */
  @java.lang.Override public com.kklab.vd.kumoi.proto.Role getRoleIndicator() {
    @SuppressWarnings("deprecation")
    com.kklab.vd.kumoi.proto.Role result = com.kklab.vd.kumoi.proto.Role.valueOf(roleIndicator_);
    return result == null ? com.kklab.vd.kumoi.proto.Role.UNRECOGNIZED : result;
  }

  public static final int METADATA_FIELD_NUMBER = 10;
  private com.google.protobuf.Struct metadata_;
  /**
   * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  public static final int SKILL_FIELD_NUMBER = 11;
  private com.kklab.vd.kumoi.proto.Skill skill_;
  /**
   * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
   * @return Whether the skill field is set.
   */
  @java.lang.Override
  public boolean hasSkill() {
    return skill_ != null;
  }
  /**
   * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
   * @return The skill.
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Skill getSkill() {
    return skill_ == null ? com.kklab.vd.kumoi.proto.Skill.getDefaultInstance() : skill_;
  }
  /**
   * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.SkillOrBuilder getSkillOrBuilder() {
    return getSkill();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChannelIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, channelId_);
    }
    if (!getFromSessionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromSession_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
    }
    if (offset_ != 0L) {
      output.writeInt64(5, offset_);
    }
    if (!getSubjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, subject_);
    }
    if (!getSubjectNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, subjectName_);
    }
    if (sequential_ != false) {
      output.writeBool(8, sequential_);
    }
    if (roleIndicator_ != com.kklab.vd.kumoi.proto.Role.RoleAll.getNumber()) {
      output.writeEnum(9, roleIndicator_);
    }
    if (metadata_ != null) {
      output.writeMessage(10, getMetadata());
    }
    if (skill_ != null) {
      output.writeMessage(11, getSkill());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChannelIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, channelId_);
    }
    if (!getFromSessionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromSession_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, offset_);
    }
    if (!getSubjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, subject_);
    }
    if (!getSubjectNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, subjectName_);
    }
    if (sequential_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, sequential_);
    }
    if (roleIndicator_ != com.kklab.vd.kumoi.proto.Role.RoleAll.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, roleIndicator_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getMetadata());
    }
    if (skill_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getSkill());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kklab.vd.kumoi.proto.ChannelMessage)) {
      return super.equals(obj);
    }
    com.kklab.vd.kumoi.proto.ChannelMessage other = (com.kklab.vd.kumoi.proto.ChannelMessage) obj;

    if (!getChannelId()
        .equals(other.getChannelId())) return false;
    if (!getFromSession()
        .equals(other.getFromSession())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (!getSubject()
        .equals(other.getSubject())) return false;
    if (!getSubjectName()
        .equals(other.getSubjectName())) return false;
    if (getSequential()
        != other.getSequential()) return false;
    if (roleIndicator_ != other.roleIndicator_) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (hasSkill() != other.hasSkill()) return false;
    if (hasSkill()) {
      if (!getSkill()
          .equals(other.getSkill())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getChannelId().hashCode();
    hash = (37 * hash) + FROM_SESSION_FIELD_NUMBER;
    hash = (53 * hash) + getFromSession().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + SUBJECT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSubjectName().hashCode();
    hash = (37 * hash) + SEQUENTIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSequential());
    hash = (37 * hash) + ROLEINDICATOR_FIELD_NUMBER;
    hash = (53 * hash) + roleIndicator_;
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (hasSkill()) {
      hash = (37 * hash) + SKILL_FIELD_NUMBER;
      hash = (53 * hash) + getSkill().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.ChannelMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kklab.vd.kumoi.proto.ChannelMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omega.ChannelMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omega.ChannelMessage)
      com.kklab.vd.kumoi.proto.ChannelMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_ChannelMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_ChannelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kklab.vd.kumoi.proto.ChannelMessage.class, com.kklab.vd.kumoi.proto.ChannelMessage.Builder.class);
    }

    // Construct using com.kklab.vd.kumoi.proto.ChannelMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      channelId_ = "";

      fromSession_ = "";

      message_ = "";

      offset_ = 0L;

      subject_ = "";

      subjectName_ = "";

      sequential_ = false;

      roleIndicator_ = 0;

      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      if (skillBuilder_ == null) {
        skill_ = null;
      } else {
        skill_ = null;
        skillBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_ChannelMessage_descriptor;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.ChannelMessage getDefaultInstanceForType() {
      return com.kklab.vd.kumoi.proto.ChannelMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.ChannelMessage build() {
      com.kklab.vd.kumoi.proto.ChannelMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.ChannelMessage buildPartial() {
      com.kklab.vd.kumoi.proto.ChannelMessage result = new com.kklab.vd.kumoi.proto.ChannelMessage(this);
      result.channelId_ = channelId_;
      result.fromSession_ = fromSession_;
      result.message_ = message_;
      result.offset_ = offset_;
      result.subject_ = subject_;
      result.subjectName_ = subjectName_;
      result.sequential_ = sequential_;
      result.roleIndicator_ = roleIndicator_;
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      if (skillBuilder_ == null) {
        result.skill_ = skill_;
      } else {
        result.skill_ = skillBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kklab.vd.kumoi.proto.ChannelMessage) {
        return mergeFrom((com.kklab.vd.kumoi.proto.ChannelMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kklab.vd.kumoi.proto.ChannelMessage other) {
      if (other == com.kklab.vd.kumoi.proto.ChannelMessage.getDefaultInstance()) return this;
      if (!other.getChannelId().isEmpty()) {
        channelId_ = other.channelId_;
        onChanged();
      }
      if (!other.getFromSession().isEmpty()) {
        fromSession_ = other.fromSession_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        onChanged();
      }
      if (!other.getSubjectName().isEmpty()) {
        subjectName_ = other.subjectName_;
        onChanged();
      }
      if (other.getSequential() != false) {
        setSequential(other.getSequential());
      }
      if (other.roleIndicator_ != 0) {
        setRoleIndicatorValue(other.getRoleIndicatorValue());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.hasSkill()) {
        mergeSkill(other.getSkill());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kklab.vd.kumoi.proto.ChannelMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kklab.vd.kumoi.proto.ChannelMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <code>string channel_id = 2[json_name = "ch"];</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string channel_id = 2[json_name = "ch"];</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string channel_id = 2[json_name = "ch"];</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string channel_id = 2[json_name = "ch"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      
      channelId_ = getDefaultInstance().getChannelId();
      onChanged();
      return this;
    }
    /**
     * <code>string channel_id = 2[json_name = "ch"];</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channelId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fromSession_ = "";
    /**
     * <code>string from_session = 3[json_name = "fs"];</code>
     * @return The fromSession.
     */
    public java.lang.String getFromSession() {
      java.lang.Object ref = fromSession_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromSession_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from_session = 3[json_name = "fs"];</code>
     * @return The bytes for fromSession.
     */
    public com.google.protobuf.ByteString
        getFromSessionBytes() {
      java.lang.Object ref = fromSession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromSession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from_session = 3[json_name = "fs"];</code>
     * @param value The fromSession to set.
     * @return This builder for chaining.
     */
    public Builder setFromSession(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromSession_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from_session = 3[json_name = "fs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFromSession() {
      
      fromSession_ = getDefaultInstance().getFromSession();
      onChanged();
      return this;
    }
    /**
     * <code>string from_session = 3[json_name = "fs"];</code>
     * @param value The bytes for fromSession to set.
     * @return This builder for chaining.
     */
    public Builder setFromSessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromSession_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 4[json_name = "m"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 4[json_name = "m"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 4[json_name = "m"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 4[json_name = "m"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 4[json_name = "m"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>int64 offset = 5[json_name = "o", jstype = JS_STRING];</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 5[json_name = "o", jstype = JS_STRING];</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 5[json_name = "o", jstype = JS_STRING];</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     * <code>string subject = 6[json_name = "sub"];</code>
     * @return The subject.
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject = 6[json_name = "sub"];</code>
     * @return The bytes for subject.
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject = 6[json_name = "sub"];</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subject_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 6[json_name = "sub"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      
      subject_ = getDefaultInstance().getSubject();
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 6[json_name = "sub"];</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subject_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subjectName_ = "";
    /**
     * <code>string subject_name = 7[json_name = "sn"];</code>
     * @return The subjectName.
     */
    public java.lang.String getSubjectName() {
      java.lang.Object ref = subjectName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject_name = 7[json_name = "sn"];</code>
     * @return The bytes for subjectName.
     */
    public com.google.protobuf.ByteString
        getSubjectNameBytes() {
      java.lang.Object ref = subjectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject_name = 7[json_name = "sn"];</code>
     * @param value The subjectName to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subjectName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject_name = 7[json_name = "sn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectName() {
      
      subjectName_ = getDefaultInstance().getSubjectName();
      onChanged();
      return this;
    }
    /**
     * <code>string subject_name = 7[json_name = "sn"];</code>
     * @param value The bytes for subjectName to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subjectName_ = value;
      onChanged();
      return this;
    }

    private boolean sequential_ ;
    /**
     * <code>bool sequential = 8[json_name = "se"];</code>
     * @return The sequential.
     */
    @java.lang.Override
    public boolean getSequential() {
      return sequential_;
    }
    /**
     * <code>bool sequential = 8[json_name = "se"];</code>
     * @param value The sequential to set.
     * @return This builder for chaining.
     */
    public Builder setSequential(boolean value) {
      
      sequential_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool sequential = 8[json_name = "se"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSequential() {
      
      sequential_ = false;
      onChanged();
      return this;
    }

    private int roleIndicator_ = 0;
    /**
     * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
     * @return The enum numeric value on the wire for roleIndicator.
     */
    @java.lang.Override public int getRoleIndicatorValue() {
      return roleIndicator_;
    }
    /**
     * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
     * @param value The enum numeric value on the wire for roleIndicator to set.
     * @return This builder for chaining.
     */
    public Builder setRoleIndicatorValue(int value) {
      
      roleIndicator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
     * @return The roleIndicator.
     */
    @java.lang.Override
    public com.kklab.vd.kumoi.proto.Role getRoleIndicator() {
      @SuppressWarnings("deprecation")
      com.kklab.vd.kumoi.proto.Role result = com.kklab.vd.kumoi.proto.Role.valueOf(roleIndicator_);
      return result == null ? com.kklab.vd.kumoi.proto.Role.UNRECOGNIZED : result;
    }
    /**
     * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
     * @param value The roleIndicator to set.
     * @return This builder for chaining.
     */
    public Builder setRoleIndicator(com.kklab.vd.kumoi.proto.Role value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      roleIndicator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleIndicator() {
      
      roleIndicator_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            com.google.protobuf.Struct.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 10[json_name = "mta"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private com.kklab.vd.kumoi.proto.Skill skill_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Skill, com.kklab.vd.kumoi.proto.Skill.Builder, com.kklab.vd.kumoi.proto.SkillOrBuilder> skillBuilder_;
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     * @return Whether the skill field is set.
     */
    public boolean hasSkill() {
      return skillBuilder_ != null || skill_ != null;
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     * @return The skill.
     */
    public com.kklab.vd.kumoi.proto.Skill getSkill() {
      if (skillBuilder_ == null) {
        return skill_ == null ? com.kklab.vd.kumoi.proto.Skill.getDefaultInstance() : skill_;
      } else {
        return skillBuilder_.getMessage();
      }
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public Builder setSkill(com.kklab.vd.kumoi.proto.Skill value) {
      if (skillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        skill_ = value;
        onChanged();
      } else {
        skillBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public Builder setSkill(
        com.kklab.vd.kumoi.proto.Skill.Builder builderForValue) {
      if (skillBuilder_ == null) {
        skill_ = builderForValue.build();
        onChanged();
      } else {
        skillBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public Builder mergeSkill(com.kklab.vd.kumoi.proto.Skill value) {
      if (skillBuilder_ == null) {
        if (skill_ != null) {
          skill_ =
            com.kklab.vd.kumoi.proto.Skill.newBuilder(skill_).mergeFrom(value).buildPartial();
        } else {
          skill_ = value;
        }
        onChanged();
      } else {
        skillBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public Builder clearSkill() {
      if (skillBuilder_ == null) {
        skill_ = null;
        onChanged();
      } else {
        skill_ = null;
        skillBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public com.kklab.vd.kumoi.proto.Skill.Builder getSkillBuilder() {
      
      onChanged();
      return getSkillFieldBuilder().getBuilder();
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    public com.kklab.vd.kumoi.proto.SkillOrBuilder getSkillOrBuilder() {
      if (skillBuilder_ != null) {
        return skillBuilder_.getMessageOrBuilder();
      } else {
        return skill_ == null ?
            com.kklab.vd.kumoi.proto.Skill.getDefaultInstance() : skill_;
      }
    }
    /**
     * <code>.omega.Skill skill = 11[json_name = "sk"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Skill, com.kklab.vd.kumoi.proto.Skill.Builder, com.kklab.vd.kumoi.proto.SkillOrBuilder> 
        getSkillFieldBuilder() {
      if (skillBuilder_ == null) {
        skillBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.kklab.vd.kumoi.proto.Skill, com.kklab.vd.kumoi.proto.Skill.Builder, com.kklab.vd.kumoi.proto.SkillOrBuilder>(
                getSkill(),
                getParentForChildren(),
                isClean());
        skill_ = null;
      }
      return skillBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omega.ChannelMessage)
  }

  // @@protoc_insertion_point(class_scope:omega.ChannelMessage)
  private static final com.kklab.vd.kumoi.proto.ChannelMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kklab.vd.kumoi.proto.ChannelMessage();
  }

  public static com.kklab.vd.kumoi.proto.ChannelMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChannelMessage>() {
    @java.lang.Override
    public ChannelMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kklab.vd.kumoi.proto.ChannelMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

