// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface CloseVoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.CloseVote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The voteId.
   */
  java.lang.String getVoteId();
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The bytes for voteId.
   */
  com.google.protobuf.ByteString
      getVoteIdBytes();

  /**
   * <code>string key = 2[json_name = "k"];</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2[json_name = "k"];</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
