// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error_level = 1[json_name = "error_level"];</code>
   * @return The errorLevel.
   */
  java.lang.String getErrorLevel();
  /**
   * <code>string error_level = 1[json_name = "error_level"];</code>
   * @return The bytes for errorLevel.
   */
  com.google.protobuf.ByteString
      getErrorLevelBytes();

  /**
   * <code>string error_category = 2[json_name = "error_category"];</code>
   * @return The errorCategory.
   */
  java.lang.String getErrorCategory();
  /**
   * <code>string error_category = 2[json_name = "error_category"];</code>
   * @return The bytes for errorCategory.
   */
  com.google.protobuf.ByteString
      getErrorCategoryBytes();

  /**
   * <code>string error_code = 3[json_name = "error_code"];</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string error_code = 3[json_name = "error_code"];</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string error_message = 4[json_name = "message"];</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 4[json_name = "message"];</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>int32 status_code = 5[json_name = "status_code"];</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>string name = 6[json_name = "error"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 6[json_name = "error"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 7[json_name = "error_description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 7[json_name = "error_description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Struct data = 8[json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Struct data = 8[json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <code>.google.protobuf.Struct data = 8[json_name = "data"];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();
}
