// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface GetSessionMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.GetSessionMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "d"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "d"];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "d"];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();

  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string name = 4[json_name = "n"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4[json_name = "n"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
