// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string subject_name = 4[json_name = "sn"];</code>
   * @return The subjectName.
   */
  java.lang.String getSubjectName();
  /**
   * <code>string subject_name = 4[json_name = "sn"];</code>
   * @return The bytes for subjectName.
   */
  com.google.protobuf.ByteString
      getSubjectNameBytes();

  /**
   * <code>string service_name = 20[json_name = "srn"];</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 20[json_name = "srn"];</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_version = 21[json_name = "srv"];</code>
   * @return The serviceVersion.
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string service_version = 21[json_name = "srv"];</code>
   * @return The bytes for serviceVersion.
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();

  /**
   * <code>string service_node_name = 22[json_name = "srnn"];</code>
   * @return The serviceNodeName.
   */
  java.lang.String getServiceNodeName();
  /**
   * <code>string service_node_name = 22[json_name = "srnn"];</code>
   * @return The bytes for serviceNodeName.
   */
  com.google.protobuf.ByteString
      getServiceNodeNameBytes();
}
