// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.Pong)
    com.google.protobuf.MessageOrBuilder {
}
