// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

/**
 * Protobuf enum {@code omega.Role}
 */
public enum Role
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RoleAll = 0;</code>
   */
  RoleAll(0),
  /**
   * <code>RoleAdmin = 1;</code>
   */
  RoleAdmin(1),
  /**
   * <code>RoleOwner = 2;</code>
   */
  RoleOwner(2),
  /**
   * <code>RoleParticipator = 3;</code>
   */
  RoleParticipator(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RoleAll = 0;</code>
   */
  public static final int RoleAll_VALUE = 0;
  /**
   * <code>RoleAdmin = 1;</code>
   */
  public static final int RoleAdmin_VALUE = 1;
  /**
   * <code>RoleOwner = 2;</code>
   */
  public static final int RoleOwner_VALUE = 2;
  /**
   * <code>RoleParticipator = 3;</code>
   */
  public static final int RoleParticipator_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Role valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Role forNumber(int value) {
    switch (value) {
      case 0: return RoleAll;
      case 1: return RoleAdmin;
      case 2: return RoleOwner;
      case 3: return RoleParticipator;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Role>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Role> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Role>() {
          public Role findValueByNumber(int number) {
            return Role.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.kklab.vd.kumoi.proto.Omega.getDescriptor().getEnumTypes().get(0);
  }

  private static final Role[] VALUES = values();

  public static Role valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Role(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:omega.Role)
}

