// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface ServerTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.ServerTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 unix_nano = 2[json_name = "n", jstype = JS_STRING];</code>
   * @return The unixNano.
   */
  long getUnixNano();

  /**
   * <code>int64 unix_timestamp = 3[json_name = "t", jstype = JS_STRING];</code>
   * @return The unixTimestamp.
   */
  long getUnixTimestamp();
}
