// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface SessionsMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.SessionsMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_session = 2[json_name = "fs"];</code>
   * @return The fromSession.
   */
  java.lang.String getFromSession();
  /**
   * <code>string from_session = 2[json_name = "fs"];</code>
   * @return The bytes for fromSession.
   */
  com.google.protobuf.ByteString
      getFromSessionBytes();

  /**
   * <code>repeated string to_sessions = 3[json_name = "tss"];</code>
   * @return A list containing the toSessions.
   */
  java.util.List<java.lang.String>
      getToSessionsList();
  /**
   * <code>repeated string to_sessions = 3[json_name = "tss"];</code>
   * @return The count of toSessions.
   */
  int getToSessionsCount();
  /**
   * <code>repeated string to_sessions = 3[json_name = "tss"];</code>
   * @param index The index of the element to return.
   * @return The toSessions at the given index.
   */
  java.lang.String getToSessions(int index);
  /**
   * <code>repeated string to_sessions = 3[json_name = "tss"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the toSessions at the given index.
   */
  com.google.protobuf.ByteString
      getToSessionsBytes(int index);

  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *  google.protobuf.Struct metadata = 10 [json_name = "mta"];
   *  Skill skill = 11 [json_name = "sk"];
   * </pre>
   *
   * <code>bool sequential = 8[json_name = "se"];</code>
   * @return The sequential.
   */
  boolean getSequential();
}
