// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface StackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.Stack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stack_count = 2[json_name = "c"];</code>
   * @return The stackCount.
   */
  int getStackCount();

  /**
   * <code>repeated .omega.TransitFrame frames = 3[json_name = "f"];</code>
   */
  java.util.List<com.kklab.vd.kumoi.proto.TransitFrame> 
      getFramesList();
  /**
   * <code>repeated .omega.TransitFrame frames = 3[json_name = "f"];</code>
   */
  com.kklab.vd.kumoi.proto.TransitFrame getFrames(int index);
  /**
   * <code>repeated .omega.TransitFrame frames = 3[json_name = "f"];</code>
   */
  int getFramesCount();
  /**
   * <code>repeated .omega.TransitFrame frames = 3[json_name = "f"];</code>
   */
  java.util.List<? extends com.kklab.vd.kumoi.proto.TransitFrameOrBuilder> 
      getFramesOrBuilderList();
  /**
   * <code>repeated .omega.TransitFrame frames = 3[json_name = "f"];</code>
   */
  com.kklab.vd.kumoi.proto.TransitFrameOrBuilder getFramesOrBuilder(
      int index);
}
