// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

/**
 * Protobuf type {@code omega.Tagging}
 */
public final class Tagging extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omega.Tagging)
    TaggingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tagging.newBuilder() to construct.
  private Tagging(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tagging() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tagging();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Tagging(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder subBuilder = null;
            if (dictionary_ != null) {
              subBuilder = dictionary_.toBuilder();
            }
            dictionary_ = input.readMessage(com.kklab.vd.kumoi.proto.Tagging.Dictionary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dictionary_);
              dictionary_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kklab.vd.kumoi.proto.Tagging.class, com.kklab.vd.kumoi.proto.Tagging.Builder.class);
  }

  public interface DictionaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:omega.Tagging.Dictionary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @return A list containing the ids.
     */
    java.util.List<java.lang.String>
        getIdsList();
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @return The count of ids.
     */
    int getIdsCount();
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    java.lang.String getIds(int index);
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the ids at the given index.
     */
    com.google.protobuf.ByteString
        getIdsBytes(int index);

    /**
     * <code>bool block = 2[json_name = "b"];</code>
     * @return The block.
     */
    boolean getBlock();
  }
  /**
   * Protobuf type {@code omega.Tagging.Dictionary}
   */
  public static final class Dictionary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:omega.Tagging.Dictionary)
      DictionaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dictionary.newBuilder() to construct.
    private Dictionary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dictionary() {
      ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dictionary();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dictionary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ids_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ids_.add(s);
              break;
            }
            case 16: {

              block_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ids_ = ids_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_Dictionary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_Dictionary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kklab.vd.kumoi.proto.Tagging.Dictionary.class, com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder.class);
    }

    public static final int IDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList ids_;
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @return A list containing the ids.
     */
    public com.google.protobuf.ProtocolStringList
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @return The count of ids.
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    public java.lang.String getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated string ids = 1[json_name = "i"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the ids at the given index.
     */
    public com.google.protobuf.ByteString
        getIdsBytes(int index) {
      return ids_.getByteString(index);
    }

    public static final int BLOCK_FIELD_NUMBER = 2;
    private boolean block_;
    /**
     * <code>bool block = 2[json_name = "b"];</code>
     * @return The block.
     */
    @java.lang.Override
    public boolean getBlock() {
      return block_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ids_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ids_.getRaw(i));
      }
      if (block_ != false) {
        output.writeBool(2, block_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += computeStringSizeNoTag(ids_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      if (block_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, block_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kklab.vd.kumoi.proto.Tagging.Dictionary)) {
        return super.equals(obj);
      }
      com.kklab.vd.kumoi.proto.Tagging.Dictionary other = (com.kklab.vd.kumoi.proto.Tagging.Dictionary) obj;

      if (!getIdsList()
          .equals(other.getIdsList())) return false;
      if (getBlock()
          != other.getBlock()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdsCount() > 0) {
        hash = (37 * hash) + IDS_FIELD_NUMBER;
        hash = (53 * hash) + getIdsList().hashCode();
      }
      hash = (37 * hash) + BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBlock());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kklab.vd.kumoi.proto.Tagging.Dictionary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code omega.Tagging.Dictionary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:omega.Tagging.Dictionary)
        com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_Dictionary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_Dictionary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kklab.vd.kumoi.proto.Tagging.Dictionary.class, com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder.class);
      }

      // Construct using com.kklab.vd.kumoi.proto.Tagging.Dictionary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        block_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_Dictionary_descriptor;
      }

      @java.lang.Override
      public com.kklab.vd.kumoi.proto.Tagging.Dictionary getDefaultInstanceForType() {
        return com.kklab.vd.kumoi.proto.Tagging.Dictionary.getDefaultInstance();
      }

      @java.lang.Override
      public com.kklab.vd.kumoi.proto.Tagging.Dictionary build() {
        com.kklab.vd.kumoi.proto.Tagging.Dictionary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kklab.vd.kumoi.proto.Tagging.Dictionary buildPartial() {
        com.kklab.vd.kumoi.proto.Tagging.Dictionary result = new com.kklab.vd.kumoi.proto.Tagging.Dictionary(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          ids_ = ids_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        result.block_ = block_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kklab.vd.kumoi.proto.Tagging.Dictionary) {
          return mergeFrom((com.kklab.vd.kumoi.proto.Tagging.Dictionary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kklab.vd.kumoi.proto.Tagging.Dictionary other) {
        if (other == com.kklab.vd.kumoi.proto.Tagging.Dictionary.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        if (other.getBlock() != false) {
          setBlock(other.getBlock());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kklab.vd.kumoi.proto.Tagging.Dictionary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kklab.vd.kumoi.proto.Tagging.Dictionary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ids_ = new com.google.protobuf.LazyStringArrayList(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @return A list containing the ids.
       */
      public com.google.protobuf.ProtocolStringList
          getIdsList() {
        return ids_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @return The count of ids.
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param index The index of the element to return.
       * @return The ids at the given index.
       */
      public java.lang.String getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param index The index of the value to return.
       * @return The bytes of the ids at the given index.
       */
      public com.google.protobuf.ByteString
          getIdsBytes(int index) {
        return ids_.getByteString(index);
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param index The index to set the value at.
       * @param value The ids to set.
       * @return This builder for chaining.
       */
      public Builder setIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param value The ids to add.
       * @return This builder for chaining.
       */
      public Builder addIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param values The ids to add.
       * @return This builder for chaining.
       */
      public Builder addAllIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIds() {
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1[json_name = "i"];</code>
       * @param value The bytes of the ids to add.
       * @return This builder for chaining.
       */
      public Builder addIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }

      private boolean block_ ;
      /**
       * <code>bool block = 2[json_name = "b"];</code>
       * @return The block.
       */
      @java.lang.Override
      public boolean getBlock() {
        return block_;
      }
      /**
       * <code>bool block = 2[json_name = "b"];</code>
       * @param value The block to set.
       * @return This builder for chaining.
       */
      public Builder setBlock(boolean value) {
        
        block_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool block = 2[json_name = "b"];</code>
       * @return This builder for chaining.
       */
      public Builder clearBlock() {
        
        block_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:omega.Tagging.Dictionary)
    }

    // @@protoc_insertion_point(class_scope:omega.Tagging.Dictionary)
    private static final com.kklab.vd.kumoi.proto.Tagging.Dictionary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kklab.vd.kumoi.proto.Tagging.Dictionary();
    }

    public static com.kklab.vd.kumoi.proto.Tagging.Dictionary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dictionary>
        PARSER = new com.google.protobuf.AbstractParser<Dictionary>() {
      @java.lang.Override
      public Dictionary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dictionary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dictionary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dictionary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.Tagging.Dictionary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DICTIONARY_FIELD_NUMBER = 1;
  private com.kklab.vd.kumoi.proto.Tagging.Dictionary dictionary_;
  /**
   * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
   * @return Whether the dictionary field is set.
   */
  @java.lang.Override
  public boolean hasDictionary() {
    return dictionary_ != null;
  }
  /**
   * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
   * @return The dictionary.
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Tagging.Dictionary getDictionary() {
    return dictionary_ == null ? com.kklab.vd.kumoi.proto.Tagging.Dictionary.getDefaultInstance() : dictionary_;
  }
  /**
   * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder getDictionaryOrBuilder() {
    return getDictionary();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dictionary_ != null) {
      output.writeMessage(1, getDictionary());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dictionary_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDictionary());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kklab.vd.kumoi.proto.Tagging)) {
      return super.equals(obj);
    }
    com.kklab.vd.kumoi.proto.Tagging other = (com.kklab.vd.kumoi.proto.Tagging) obj;

    if (hasDictionary() != other.hasDictionary()) return false;
    if (hasDictionary()) {
      if (!getDictionary()
          .equals(other.getDictionary())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDictionary()) {
      hash = (37 * hash) + DICTIONARY_FIELD_NUMBER;
      hash = (53 * hash) + getDictionary().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.Tagging parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kklab.vd.kumoi.proto.Tagging prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omega.Tagging}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omega.Tagging)
      com.kklab.vd.kumoi.proto.TaggingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kklab.vd.kumoi.proto.Tagging.class, com.kklab.vd.kumoi.proto.Tagging.Builder.class);
    }

    // Construct using com.kklab.vd.kumoi.proto.Tagging.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dictionaryBuilder_ == null) {
        dictionary_ = null;
      } else {
        dictionary_ = null;
        dictionaryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_Tagging_descriptor;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.Tagging getDefaultInstanceForType() {
      return com.kklab.vd.kumoi.proto.Tagging.getDefaultInstance();
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.Tagging build() {
      com.kklab.vd.kumoi.proto.Tagging result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.Tagging buildPartial() {
      com.kklab.vd.kumoi.proto.Tagging result = new com.kklab.vd.kumoi.proto.Tagging(this);
      if (dictionaryBuilder_ == null) {
        result.dictionary_ = dictionary_;
      } else {
        result.dictionary_ = dictionaryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kklab.vd.kumoi.proto.Tagging) {
        return mergeFrom((com.kklab.vd.kumoi.proto.Tagging)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kklab.vd.kumoi.proto.Tagging other) {
      if (other == com.kklab.vd.kumoi.proto.Tagging.getDefaultInstance()) return this;
      if (other.hasDictionary()) {
        mergeDictionary(other.getDictionary());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kklab.vd.kumoi.proto.Tagging parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kklab.vd.kumoi.proto.Tagging) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.kklab.vd.kumoi.proto.Tagging.Dictionary dictionary_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Tagging.Dictionary, com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder, com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder> dictionaryBuilder_;
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     * @return Whether the dictionary field is set.
     */
    public boolean hasDictionary() {
      return dictionaryBuilder_ != null || dictionary_ != null;
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     * @return The dictionary.
     */
    public com.kklab.vd.kumoi.proto.Tagging.Dictionary getDictionary() {
      if (dictionaryBuilder_ == null) {
        return dictionary_ == null ? com.kklab.vd.kumoi.proto.Tagging.Dictionary.getDefaultInstance() : dictionary_;
      } else {
        return dictionaryBuilder_.getMessage();
      }
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public Builder setDictionary(com.kklab.vd.kumoi.proto.Tagging.Dictionary value) {
      if (dictionaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dictionary_ = value;
        onChanged();
      } else {
        dictionaryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public Builder setDictionary(
        com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder builderForValue) {
      if (dictionaryBuilder_ == null) {
        dictionary_ = builderForValue.build();
        onChanged();
      } else {
        dictionaryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public Builder mergeDictionary(com.kklab.vd.kumoi.proto.Tagging.Dictionary value) {
      if (dictionaryBuilder_ == null) {
        if (dictionary_ != null) {
          dictionary_ =
            com.kklab.vd.kumoi.proto.Tagging.Dictionary.newBuilder(dictionary_).mergeFrom(value).buildPartial();
        } else {
          dictionary_ = value;
        }
        onChanged();
      } else {
        dictionaryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public Builder clearDictionary() {
      if (dictionaryBuilder_ == null) {
        dictionary_ = null;
        onChanged();
      } else {
        dictionary_ = null;
        dictionaryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder getDictionaryBuilder() {
      
      onChanged();
      return getDictionaryFieldBuilder().getBuilder();
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    public com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder getDictionaryOrBuilder() {
      if (dictionaryBuilder_ != null) {
        return dictionaryBuilder_.getMessageOrBuilder();
      } else {
        return dictionary_ == null ?
            com.kklab.vd.kumoi.proto.Tagging.Dictionary.getDefaultInstance() : dictionary_;
      }
    }
    /**
     * <code>.omega.Tagging.Dictionary dictionary = 1[json_name = "d"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Tagging.Dictionary, com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder, com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder> 
        getDictionaryFieldBuilder() {
      if (dictionaryBuilder_ == null) {
        dictionaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.kklab.vd.kumoi.proto.Tagging.Dictionary, com.kklab.vd.kumoi.proto.Tagging.Dictionary.Builder, com.kklab.vd.kumoi.proto.Tagging.DictionaryOrBuilder>(
                getDictionary(),
                getParentForChildren(),
                isClean());
        dictionary_ = null;
      }
      return dictionaryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omega.Tagging)
  }

  // @@protoc_insertion_point(class_scope:omega.Tagging)
  private static final com.kklab.vd.kumoi.proto.Tagging DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kklab.vd.kumoi.proto.Tagging();
  }

  public static com.kklab.vd.kumoi.proto.Tagging getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tagging>
      PARSER = new com.google.protobuf.AbstractParser<Tagging>() {
    @java.lang.Override
    public Tagging parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Tagging(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Tagging> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tagging> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Tagging getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

