// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface TransitFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.TransitFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 transit_id = 1[json_name = "i", jstype = JS_STRING];</code>
   * @return The transitId.
   */
  long getTransitId();

  /**
   * <code>.omega.TransitFrame.FrameClass class = 2[json_name = "c"];</code>
   * @return The enum numeric value on the wire for class.
   */
  int getClass_Value();
  /**
   * <code>.omega.TransitFrame.FrameClass class = 2[json_name = "c"];</code>
   * @return The class.
   */
  com.kklab.vd.kumoi.proto.TransitFrame.FrameClass getClass_();

  /**
   * <code>.omega.TransitFrame.Version version = 3[json_name = "v"];</code>
   * @return The enum numeric value on the wire for version.
   */
  int getVersionValue();
  /**
   * <code>.omega.TransitFrame.Version version = 3[json_name = "v"];</code>
   * @return The version.
   */
  com.kklab.vd.kumoi.proto.TransitFrame.Version getVersion();

  /**
   * <code>int64 timestamp = 4[json_name = "t", jstype = JS_STRING];</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.omega.Error err = 5[json_name = "e"];</code>
   * @return Whether the err field is set.
   */
  boolean hasErr();
  /**
   * <code>.omega.Error err = 5[json_name = "e"];</code>
   * @return The err.
   */
  com.kklab.vd.kumoi.proto.Error getErr();
  /**
   * <code>.omega.Error err = 5[json_name = "e"];</code>
   */
  com.kklab.vd.kumoi.proto.ErrorOrBuilder getErrOrBuilder();

  /**
   * <code>bytes message_id = 6[json_name = "m"];</code>
   * @return The messageId.
   */
  com.google.protobuf.ByteString getMessageId();

  /**
   * <code>bytes referer_message_id = 7[json_name = "rm"];</code>
   * @return The refererMessageId.
   */
  com.google.protobuf.ByteString getRefererMessageId();

  /**
   * <code>.omega.Close Close = 8;</code>
   * @return Whether the close field is set.
   */
  boolean hasClose();
  /**
   * <code>.omega.Close Close = 8;</code>
   * @return The close.
   */
  com.kklab.vd.kumoi.proto.Close getClose();
  /**
   * <code>.omega.Close Close = 8;</code>
   */
  com.kklab.vd.kumoi.proto.CloseOrBuilder getCloseOrBuilder();

  /**
   * <code>.omega.Ping Ping = 9;</code>
   * @return Whether the ping field is set.
   */
  boolean hasPing();
  /**
   * <code>.omega.Ping Ping = 9;</code>
   * @return The ping.
   */
  com.kklab.vd.kumoi.proto.Ping getPing();
  /**
   * <code>.omega.Ping Ping = 9;</code>
   */
  com.kklab.vd.kumoi.proto.PingOrBuilder getPingOrBuilder();

  /**
   * <code>.omega.Pong Pong = 10;</code>
   * @return Whether the pong field is set.
   */
  boolean hasPong();
  /**
   * <code>.omega.Pong Pong = 10;</code>
   * @return The pong.
   */
  com.kklab.vd.kumoi.proto.Pong getPong();
  /**
   * <code>.omega.Pong Pong = 10;</code>
   */
  com.kklab.vd.kumoi.proto.PongOrBuilder getPongOrBuilder();

  /**
   * <code>.omega.Stack Stack = 16;</code>
   * @return Whether the stack field is set.
   */
  boolean hasStack();
  /**
   * <code>.omega.Stack Stack = 16;</code>
   * @return The stack.
   */
  com.kklab.vd.kumoi.proto.Stack getStack();
  /**
   * <code>.omega.Stack Stack = 16;</code>
   */
  com.kklab.vd.kumoi.proto.StackOrBuilder getStackOrBuilder();

  /**
   * <code>.omega.Broadcast Broadcast = 18;</code>
   * @return Whether the broadcast field is set.
   */
  boolean hasBroadcast();
  /**
   * <code>.omega.Broadcast Broadcast = 18;</code>
   * @return The broadcast.
   */
  com.kklab.vd.kumoi.proto.Broadcast getBroadcast();
  /**
   * <code>.omega.Broadcast Broadcast = 18;</code>
   */
  com.kklab.vd.kumoi.proto.BroadcastOrBuilder getBroadcastOrBuilder();

  /**
   * <code>.omega.Hello Hello = 19;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.omega.Hello Hello = 19;</code>
   * @return The hello.
   */
  com.kklab.vd.kumoi.proto.Hello getHello();
  /**
   * <code>.omega.Hello Hello = 19;</code>
   */
  com.kklab.vd.kumoi.proto.HelloOrBuilder getHelloOrBuilder();

  /**
   * <code>.omega.ServerTime ServerTime = 20;</code>
   * @return Whether the serverTime field is set.
   */
  boolean hasServerTime();
  /**
   * <code>.omega.ServerTime ServerTime = 20;</code>
   * @return The serverTime.
   */
  com.kklab.vd.kumoi.proto.ServerTime getServerTime();
  /**
   * <code>.omega.ServerTime ServerTime = 20;</code>
   */
  com.kklab.vd.kumoi.proto.ServerTimeOrBuilder getServerTimeOrBuilder();

  /**
   * <code>.omega.PlaybackChannelMessage PlaybackChannelMessage = 100;</code>
   * @return Whether the playbackChannelMessage field is set.
   */
  boolean hasPlaybackChannelMessage();
  /**
   * <code>.omega.PlaybackChannelMessage PlaybackChannelMessage = 100;</code>
   * @return The playbackChannelMessage.
   */
  com.kklab.vd.kumoi.proto.PlaybackChannelMessage getPlaybackChannelMessage();
  /**
   * <code>.omega.PlaybackChannelMessage PlaybackChannelMessage = 100;</code>
   */
  com.kklab.vd.kumoi.proto.PlaybackChannelMessageOrBuilder getPlaybackChannelMessageOrBuilder();

  /**
   * <code>.omega.GetChannelMeta GetChannelMeta = 200;</code>
   * @return Whether the getChannelMeta field is set.
   */
  boolean hasGetChannelMeta();
  /**
   * <code>.omega.GetChannelMeta GetChannelMeta = 200;</code>
   * @return The getChannelMeta.
   */
  com.kklab.vd.kumoi.proto.GetChannelMeta getGetChannelMeta();
  /**
   * <code>.omega.GetChannelMeta GetChannelMeta = 200;</code>
   */
  com.kklab.vd.kumoi.proto.GetChannelMetaOrBuilder getGetChannelMetaOrBuilder();

  /**
   * <code>.omega.SetChannelMeta SetChannelMeta = 201;</code>
   * @return Whether the setChannelMeta field is set.
   */
  boolean hasSetChannelMeta();
  /**
   * <code>.omega.SetChannelMeta SetChannelMeta = 201;</code>
   * @return The setChannelMeta.
   */
  com.kklab.vd.kumoi.proto.SetChannelMeta getSetChannelMeta();
  /**
   * <code>.omega.SetChannelMeta SetChannelMeta = 201;</code>
   */
  com.kklab.vd.kumoi.proto.SetChannelMetaOrBuilder getSetChannelMetaOrBuilder();

  /**
   * <code>.omega.CreateChannel CreateChannel = 202;</code>
   * @return Whether the createChannel field is set.
   */
  boolean hasCreateChannel();
  /**
   * <code>.omega.CreateChannel CreateChannel = 202;</code>
   * @return The createChannel.
   */
  com.kklab.vd.kumoi.proto.CreateChannel getCreateChannel();
  /**
   * <code>.omega.CreateChannel CreateChannel = 202;</code>
   */
  com.kklab.vd.kumoi.proto.CreateChannelOrBuilder getCreateChannelOrBuilder();

  /**
   * <code>.omega.JoinChannel JoinChannel = 203;</code>
   * @return Whether the joinChannel field is set.
   */
  boolean hasJoinChannel();
  /**
   * <code>.omega.JoinChannel JoinChannel = 203;</code>
   * @return The joinChannel.
   */
  com.kklab.vd.kumoi.proto.JoinChannel getJoinChannel();
  /**
   * <code>.omega.JoinChannel JoinChannel = 203;</code>
   */
  com.kklab.vd.kumoi.proto.JoinChannelOrBuilder getJoinChannelOrBuilder();

  /**
   * <code>.omega.LeaveChannel LeaveChannel = 204;</code>
   * @return Whether the leaveChannel field is set.
   */
  boolean hasLeaveChannel();
  /**
   * <code>.omega.LeaveChannel LeaveChannel = 204;</code>
   * @return The leaveChannel.
   */
  com.kklab.vd.kumoi.proto.LeaveChannel getLeaveChannel();
  /**
   * <code>.omega.LeaveChannel LeaveChannel = 204;</code>
   */
  com.kklab.vd.kumoi.proto.LeaveChannelOrBuilder getLeaveChannelOrBuilder();

  /**
   * <code>.omega.CloseChannel CloseChannel = 205;</code>
   * @return Whether the closeChannel field is set.
   */
  boolean hasCloseChannel();
  /**
   * <code>.omega.CloseChannel CloseChannel = 205;</code>
   * @return The closeChannel.
   */
  com.kklab.vd.kumoi.proto.CloseChannel getCloseChannel();
  /**
   * <code>.omega.CloseChannel CloseChannel = 205;</code>
   */
  com.kklab.vd.kumoi.proto.CloseChannelOrBuilder getCloseChannelOrBuilder();

  /**
   * <code>.omega.ChannelMessage ChannelMessage = 206;</code>
   * @return Whether the channelMessage field is set.
   */
  boolean hasChannelMessage();
  /**
   * <code>.omega.ChannelMessage ChannelMessage = 206;</code>
   * @return The channelMessage.
   */
  com.kklab.vd.kumoi.proto.ChannelMessage getChannelMessage();
  /**
   * <code>.omega.ChannelMessage ChannelMessage = 206;</code>
   */
  com.kklab.vd.kumoi.proto.ChannelMessageOrBuilder getChannelMessageOrBuilder();

  /**
   * <code>.omega.ChannelCount ChannelCount = 208;</code>
   * @return Whether the channelCount field is set.
   */
  boolean hasChannelCount();
  /**
   * <code>.omega.ChannelCount ChannelCount = 208;</code>
   * @return The channelCount.
   */
  com.kklab.vd.kumoi.proto.ChannelCount getChannelCount();
  /**
   * <code>.omega.ChannelCount ChannelCount = 208;</code>
   */
  com.kklab.vd.kumoi.proto.ChannelCountOrBuilder getChannelCountOrBuilder();

  /**
   * <code>.omega.ChannelOwnerMessage ChannelOwnerMessage = 209;</code>
   * @return Whether the channelOwnerMessage field is set.
   */
  boolean hasChannelOwnerMessage();
  /**
   * <code>.omega.ChannelOwnerMessage ChannelOwnerMessage = 209;</code>
   * @return The channelOwnerMessage.
   */
  com.kklab.vd.kumoi.proto.ChannelOwnerMessage getChannelOwnerMessage();
  /**
   * <code>.omega.ChannelOwnerMessage ChannelOwnerMessage = 209;</code>
   */
  com.kklab.vd.kumoi.proto.ChannelOwnerMessageOrBuilder getChannelOwnerMessageOrBuilder();

  /**
   * <code>.omega.ReplayChannelMessage ReplayChannelMessage = 211;</code>
   * @return Whether the replayChannelMessage field is set.
   */
  boolean hasReplayChannelMessage();
  /**
   * <code>.omega.ReplayChannelMessage ReplayChannelMessage = 211;</code>
   * @return The replayChannelMessage.
   */
  com.kklab.vd.kumoi.proto.ReplayChannelMessage getReplayChannelMessage();
  /**
   * <code>.omega.ReplayChannelMessage ReplayChannelMessage = 211;</code>
   */
  com.kklab.vd.kumoi.proto.ReplayChannelMessageOrBuilder getReplayChannelMessageOrBuilder();

  /**
   * <code>.omega.GetVoteMeta GetVoteMeta = 230;</code>
   * @return Whether the getVoteMeta field is set.
   */
  boolean hasGetVoteMeta();
  /**
   * <code>.omega.GetVoteMeta GetVoteMeta = 230;</code>
   * @return The getVoteMeta.
   */
  com.kklab.vd.kumoi.proto.GetVoteMeta getGetVoteMeta();
  /**
   * <code>.omega.GetVoteMeta GetVoteMeta = 230;</code>
   */
  com.kklab.vd.kumoi.proto.GetVoteMetaOrBuilder getGetVoteMetaOrBuilder();

  /**
   * <code>.omega.SetVoteMeta SetVoteMeta = 231;</code>
   * @return Whether the setVoteMeta field is set.
   */
  boolean hasSetVoteMeta();
  /**
   * <code>.omega.SetVoteMeta SetVoteMeta = 231;</code>
   * @return The setVoteMeta.
   */
  com.kklab.vd.kumoi.proto.SetVoteMeta getSetVoteMeta();
  /**
   * <code>.omega.SetVoteMeta SetVoteMeta = 231;</code>
   */
  com.kklab.vd.kumoi.proto.SetVoteMetaOrBuilder getSetVoteMetaOrBuilder();

  /**
   * <code>.omega.CreateVote CreateVote = 232;</code>
   * @return Whether the createVote field is set.
   */
  boolean hasCreateVote();
  /**
   * <code>.omega.CreateVote CreateVote = 232;</code>
   * @return The createVote.
   */
  com.kklab.vd.kumoi.proto.CreateVote getCreateVote();
  /**
   * <code>.omega.CreateVote CreateVote = 232;</code>
   */
  com.kklab.vd.kumoi.proto.CreateVoteOrBuilder getCreateVoteOrBuilder();

  /**
   * <code>.omega.JoinVote JoinVote = 233;</code>
   * @return Whether the joinVote field is set.
   */
  boolean hasJoinVote();
  /**
   * <code>.omega.JoinVote JoinVote = 233;</code>
   * @return The joinVote.
   */
  com.kklab.vd.kumoi.proto.JoinVote getJoinVote();
  /**
   * <code>.omega.JoinVote JoinVote = 233;</code>
   */
  com.kklab.vd.kumoi.proto.JoinVoteOrBuilder getJoinVoteOrBuilder();

  /**
   * <code>.omega.LeaveVote LeaveVote = 234;</code>
   * @return Whether the leaveVote field is set.
   */
  boolean hasLeaveVote();
  /**
   * <code>.omega.LeaveVote LeaveVote = 234;</code>
   * @return The leaveVote.
   */
  com.kklab.vd.kumoi.proto.LeaveVote getLeaveVote();
  /**
   * <code>.omega.LeaveVote LeaveVote = 234;</code>
   */
  com.kklab.vd.kumoi.proto.LeaveVoteOrBuilder getLeaveVoteOrBuilder();

  /**
   * <code>.omega.CloseVote CloseVote = 235;</code>
   * @return Whether the closeVote field is set.
   */
  boolean hasCloseVote();
  /**
   * <code>.omega.CloseVote CloseVote = 235;</code>
   * @return The closeVote.
   */
  com.kklab.vd.kumoi.proto.CloseVote getCloseVote();
  /**
   * <code>.omega.CloseVote CloseVote = 235;</code>
   */
  com.kklab.vd.kumoi.proto.CloseVoteOrBuilder getCloseVoteOrBuilder();

  /**
   * <code>.omega.VoteMessage VoteMessage = 236;</code>
   * @return Whether the voteMessage field is set.
   */
  boolean hasVoteMessage();
  /**
   * <code>.omega.VoteMessage VoteMessage = 236;</code>
   * @return The voteMessage.
   */
  com.kklab.vd.kumoi.proto.VoteMessage getVoteMessage();
  /**
   * <code>.omega.VoteMessage VoteMessage = 236;</code>
   */
  com.kklab.vd.kumoi.proto.VoteMessageOrBuilder getVoteMessageOrBuilder();

  /**
   * <code>.omega.VoteSelect VoteSelect = 237;</code>
   * @return Whether the voteSelect field is set.
   */
  boolean hasVoteSelect();
  /**
   * <code>.omega.VoteSelect VoteSelect = 237;</code>
   * @return The voteSelect.
   */
  com.kklab.vd.kumoi.proto.VoteSelect getVoteSelect();
  /**
   * <code>.omega.VoteSelect VoteSelect = 237;</code>
   */
  com.kklab.vd.kumoi.proto.VoteSelectOrBuilder getVoteSelectOrBuilder();

  /**
   * <code>.omega.VoteCount VoteCount = 238;</code>
   * @return Whether the voteCount field is set.
   */
  boolean hasVoteCount();
  /**
   * <code>.omega.VoteCount VoteCount = 238;</code>
   * @return The voteCount.
   */
  com.kklab.vd.kumoi.proto.VoteCount getVoteCount();
  /**
   * <code>.omega.VoteCount VoteCount = 238;</code>
   */
  com.kklab.vd.kumoi.proto.VoteCountOrBuilder getVoteCountOrBuilder();

  /**
   * <code>.omega.VoteOwnerMessage VoteOwnerMessage = 239;</code>
   * @return Whether the voteOwnerMessage field is set.
   */
  boolean hasVoteOwnerMessage();
  /**
   * <code>.omega.VoteOwnerMessage VoteOwnerMessage = 239;</code>
   * @return The voteOwnerMessage.
   */
  com.kklab.vd.kumoi.proto.VoteOwnerMessage getVoteOwnerMessage();
  /**
   * <code>.omega.VoteOwnerMessage VoteOwnerMessage = 239;</code>
   */
  com.kklab.vd.kumoi.proto.VoteOwnerMessageOrBuilder getVoteOwnerMessageOrBuilder();

  /**
   * <code>.omega.VoteStatus VoteStatus = 240;</code>
   * @return Whether the voteStatus field is set.
   */
  boolean hasVoteStatus();
  /**
   * <code>.omega.VoteStatus VoteStatus = 240;</code>
   * @return The voteStatus.
   */
  com.kklab.vd.kumoi.proto.VoteStatus getVoteStatus();
  /**
   * <code>.omega.VoteStatus VoteStatus = 240;</code>
   */
  com.kklab.vd.kumoi.proto.VoteStatusOrBuilder getVoteStatusOrBuilder();

  /**
   * <code>.omega.GetSessionMeta GetSessionMeta = 250;</code>
   * @return Whether the getSessionMeta field is set.
   */
  boolean hasGetSessionMeta();
  /**
   * <code>.omega.GetSessionMeta GetSessionMeta = 250;</code>
   * @return The getSessionMeta.
   */
  com.kklab.vd.kumoi.proto.GetSessionMeta getGetSessionMeta();
  /**
   * <code>.omega.GetSessionMeta GetSessionMeta = 250;</code>
   */
  com.kklab.vd.kumoi.proto.GetSessionMetaOrBuilder getGetSessionMetaOrBuilder();

  /**
   * <code>.omega.SetSessionMeta SetSessionMeta = 251;</code>
   * @return Whether the setSessionMeta field is set.
   */
  boolean hasSetSessionMeta();
  /**
   * <code>.omega.SetSessionMeta SetSessionMeta = 251;</code>
   * @return The setSessionMeta.
   */
  com.kklab.vd.kumoi.proto.SetSessionMeta getSetSessionMeta();
  /**
   * <code>.omega.SetSessionMeta SetSessionMeta = 251;</code>
   */
  com.kklab.vd.kumoi.proto.SetSessionMetaOrBuilder getSetSessionMetaOrBuilder();

  /**
   * <code>.omega.SessionMessage SessionMessage = 252;</code>
   * @return Whether the sessionMessage field is set.
   */
  boolean hasSessionMessage();
  /**
   * <code>.omega.SessionMessage SessionMessage = 252;</code>
   * @return The sessionMessage.
   */
  com.kklab.vd.kumoi.proto.SessionMessage getSessionMessage();
  /**
   * <code>.omega.SessionMessage SessionMessage = 252;</code>
   */
  com.kklab.vd.kumoi.proto.SessionMessageOrBuilder getSessionMessageOrBuilder();

  /**
   * <code>.omega.SessionsMessage SessionsMessage = 253;</code>
   * @return Whether the sessionsMessage field is set.
   */
  boolean hasSessionsMessage();
  /**
   * <code>.omega.SessionsMessage SessionsMessage = 253;</code>
   * @return The sessionsMessage.
   */
  com.kklab.vd.kumoi.proto.SessionsMessage getSessionsMessage();
  /**
   * <code>.omega.SessionsMessage SessionsMessage = 253;</code>
   */
  com.kklab.vd.kumoi.proto.SessionsMessageOrBuilder getSessionsMessageOrBuilder();

  public com.kklab.vd.kumoi.proto.TransitFrame.DataCase getDataCase();
}
