// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

/**
 * Protobuf type {@code omega.VoteCount}
 */
public final class VoteCount extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omega.VoteCount)
    VoteCountOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VoteCount.newBuilder() to construct.
  private VoteCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoteCount() {
    voteId_ = "";
    key_ = "";
    voteOptions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VoteCount();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VoteCount(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            voteId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              voteOptions_ = new java.util.ArrayList<com.kklab.vd.kumoi.proto.Vote.Option>();
              mutable_bitField0_ |= 0x00000001;
            }
            voteOptions_.add(
                input.readMessage(com.kklab.vd.kumoi.proto.Vote.Option.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        voteOptions_ = java.util.Collections.unmodifiableList(voteOptions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_VoteCount_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_VoteCount_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kklab.vd.kumoi.proto.VoteCount.class, com.kklab.vd.kumoi.proto.VoteCount.Builder.class);
  }

  public static final int VOTE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object voteId_;
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The voteId.
   */
  @java.lang.Override
  public java.lang.String getVoteId() {
    java.lang.Object ref = voteId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voteId_ = s;
      return s;
    }
  }
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The bytes for voteId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVoteIdBytes() {
    java.lang.Object ref = voteId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voteId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 2[json_name = "k"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 2[json_name = "k"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOTE_OPTIONS_FIELD_NUMBER = 3;
  private java.util.List<com.kklab.vd.kumoi.proto.Vote.Option> voteOptions_;
  /**
   * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
   */
  @java.lang.Override
  public java.util.List<com.kklab.vd.kumoi.proto.Vote.Option> getVoteOptionsList() {
    return voteOptions_;
  }
  /**
   * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder> 
      getVoteOptionsOrBuilderList() {
    return voteOptions_;
  }
  /**
   * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
   */
  @java.lang.Override
  public int getVoteOptionsCount() {
    return voteOptions_.size();
  }
  /**
   * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Vote.Option getVoteOptions(int index) {
    return voteOptions_.get(index);
  }
  /**
   * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
   */
  @java.lang.Override
  public com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder getVoteOptionsOrBuilder(
      int index) {
    return voteOptions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVoteIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voteId_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    for (int i = 0; i < voteOptions_.size(); i++) {
      output.writeMessage(3, voteOptions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVoteIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voteId_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    for (int i = 0; i < voteOptions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, voteOptions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kklab.vd.kumoi.proto.VoteCount)) {
      return super.equals(obj);
    }
    com.kklab.vd.kumoi.proto.VoteCount other = (com.kklab.vd.kumoi.proto.VoteCount) obj;

    if (!getVoteId()
        .equals(other.getVoteId())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getVoteOptionsList()
        .equals(other.getVoteOptionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VOTE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVoteId().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (getVoteOptionsCount() > 0) {
      hash = (37 * hash) + VOTE_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getVoteOptionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kklab.vd.kumoi.proto.VoteCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kklab.vd.kumoi.proto.VoteCount prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omega.VoteCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omega.VoteCount)
      com.kklab.vd.kumoi.proto.VoteCountOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_VoteCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_VoteCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kklab.vd.kumoi.proto.VoteCount.class, com.kklab.vd.kumoi.proto.VoteCount.Builder.class);
    }

    // Construct using com.kklab.vd.kumoi.proto.VoteCount.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVoteOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      voteId_ = "";

      key_ = "";

      if (voteOptionsBuilder_ == null) {
        voteOptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        voteOptionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kklab.vd.kumoi.proto.Omega.internal_static_omega_VoteCount_descriptor;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.VoteCount getDefaultInstanceForType() {
      return com.kklab.vd.kumoi.proto.VoteCount.getDefaultInstance();
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.VoteCount build() {
      com.kklab.vd.kumoi.proto.VoteCount result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kklab.vd.kumoi.proto.VoteCount buildPartial() {
      com.kklab.vd.kumoi.proto.VoteCount result = new com.kklab.vd.kumoi.proto.VoteCount(this);
      int from_bitField0_ = bitField0_;
      result.voteId_ = voteId_;
      result.key_ = key_;
      if (voteOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          voteOptions_ = java.util.Collections.unmodifiableList(voteOptions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.voteOptions_ = voteOptions_;
      } else {
        result.voteOptions_ = voteOptionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kklab.vd.kumoi.proto.VoteCount) {
        return mergeFrom((com.kklab.vd.kumoi.proto.VoteCount)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kklab.vd.kumoi.proto.VoteCount other) {
      if (other == com.kklab.vd.kumoi.proto.VoteCount.getDefaultInstance()) return this;
      if (!other.getVoteId().isEmpty()) {
        voteId_ = other.voteId_;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (voteOptionsBuilder_ == null) {
        if (!other.voteOptions_.isEmpty()) {
          if (voteOptions_.isEmpty()) {
            voteOptions_ = other.voteOptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVoteOptionsIsMutable();
            voteOptions_.addAll(other.voteOptions_);
          }
          onChanged();
        }
      } else {
        if (!other.voteOptions_.isEmpty()) {
          if (voteOptionsBuilder_.isEmpty()) {
            voteOptionsBuilder_.dispose();
            voteOptionsBuilder_ = null;
            voteOptions_ = other.voteOptions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            voteOptionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVoteOptionsFieldBuilder() : null;
          } else {
            voteOptionsBuilder_.addAllMessages(other.voteOptions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kklab.vd.kumoi.proto.VoteCount parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kklab.vd.kumoi.proto.VoteCount) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object voteId_ = "";
    /**
     * <code>string vote_id = 1[json_name = "vt"];</code>
     * @return The voteId.
     */
    public java.lang.String getVoteId() {
      java.lang.Object ref = voteId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voteId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vote_id = 1[json_name = "vt"];</code>
     * @return The bytes for voteId.
     */
    public com.google.protobuf.ByteString
        getVoteIdBytes() {
      java.lang.Object ref = voteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vote_id = 1[json_name = "vt"];</code>
     * @param value The voteId to set.
     * @return This builder for chaining.
     */
    public Builder setVoteId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voteId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vote_id = 1[json_name = "vt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVoteId() {
      
      voteId_ = getDefaultInstance().getVoteId();
      onChanged();
      return this;
    }
    /**
     * <code>string vote_id = 1[json_name = "vt"];</code>
     * @param value The bytes for voteId to set.
     * @return This builder for chaining.
     */
    public Builder setVoteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      voteId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 2[json_name = "k"];</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 2[json_name = "k"];</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 2[json_name = "k"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2[json_name = "k"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2[json_name = "k"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.kklab.vd.kumoi.proto.Vote.Option> voteOptions_ =
      java.util.Collections.emptyList();
    private void ensureVoteOptionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        voteOptions_ = new java.util.ArrayList<com.kklab.vd.kumoi.proto.Vote.Option>(voteOptions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Vote.Option, com.kklab.vd.kumoi.proto.Vote.Option.Builder, com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder> voteOptionsBuilder_;

    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public java.util.List<com.kklab.vd.kumoi.proto.Vote.Option> getVoteOptionsList() {
      if (voteOptionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(voteOptions_);
      } else {
        return voteOptionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public int getVoteOptionsCount() {
      if (voteOptionsBuilder_ == null) {
        return voteOptions_.size();
      } else {
        return voteOptionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public com.kklab.vd.kumoi.proto.Vote.Option getVoteOptions(int index) {
      if (voteOptionsBuilder_ == null) {
        return voteOptions_.get(index);
      } else {
        return voteOptionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder setVoteOptions(
        int index, com.kklab.vd.kumoi.proto.Vote.Option value) {
      if (voteOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoteOptionsIsMutable();
        voteOptions_.set(index, value);
        onChanged();
      } else {
        voteOptionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder setVoteOptions(
        int index, com.kklab.vd.kumoi.proto.Vote.Option.Builder builderForValue) {
      if (voteOptionsBuilder_ == null) {
        ensureVoteOptionsIsMutable();
        voteOptions_.set(index, builderForValue.build());
        onChanged();
      } else {
        voteOptionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder addVoteOptions(com.kklab.vd.kumoi.proto.Vote.Option value) {
      if (voteOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoteOptionsIsMutable();
        voteOptions_.add(value);
        onChanged();
      } else {
        voteOptionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder addVoteOptions(
        int index, com.kklab.vd.kumoi.proto.Vote.Option value) {
      if (voteOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoteOptionsIsMutable();
        voteOptions_.add(index, value);
        onChanged();
      } else {
        voteOptionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder addVoteOptions(
        com.kklab.vd.kumoi.proto.Vote.Option.Builder builderForValue) {
      if (voteOptionsBuilder_ == null) {
        ensureVoteOptionsIsMutable();
        voteOptions_.add(builderForValue.build());
        onChanged();
      } else {
        voteOptionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder addVoteOptions(
        int index, com.kklab.vd.kumoi.proto.Vote.Option.Builder builderForValue) {
      if (voteOptionsBuilder_ == null) {
        ensureVoteOptionsIsMutable();
        voteOptions_.add(index, builderForValue.build());
        onChanged();
      } else {
        voteOptionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder addAllVoteOptions(
        java.lang.Iterable<? extends com.kklab.vd.kumoi.proto.Vote.Option> values) {
      if (voteOptionsBuilder_ == null) {
        ensureVoteOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, voteOptions_);
        onChanged();
      } else {
        voteOptionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder clearVoteOptions() {
      if (voteOptionsBuilder_ == null) {
        voteOptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        voteOptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public Builder removeVoteOptions(int index) {
      if (voteOptionsBuilder_ == null) {
        ensureVoteOptionsIsMutable();
        voteOptions_.remove(index);
        onChanged();
      } else {
        voteOptionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public com.kklab.vd.kumoi.proto.Vote.Option.Builder getVoteOptionsBuilder(
        int index) {
      return getVoteOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder getVoteOptionsOrBuilder(
        int index) {
      if (voteOptionsBuilder_ == null) {
        return voteOptions_.get(index);  } else {
        return voteOptionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public java.util.List<? extends com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder> 
         getVoteOptionsOrBuilderList() {
      if (voteOptionsBuilder_ != null) {
        return voteOptionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(voteOptions_);
      }
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public com.kklab.vd.kumoi.proto.Vote.Option.Builder addVoteOptionsBuilder() {
      return getVoteOptionsFieldBuilder().addBuilder(
          com.kklab.vd.kumoi.proto.Vote.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public com.kklab.vd.kumoi.proto.Vote.Option.Builder addVoteOptionsBuilder(
        int index) {
      return getVoteOptionsFieldBuilder().addBuilder(
          index, com.kklab.vd.kumoi.proto.Vote.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .omega.Vote.Option vote_options = 3[json_name = "vtos"];</code>
     */
    public java.util.List<com.kklab.vd.kumoi.proto.Vote.Option.Builder> 
         getVoteOptionsBuilderList() {
      return getVoteOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.kklab.vd.kumoi.proto.Vote.Option, com.kklab.vd.kumoi.proto.Vote.Option.Builder, com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder> 
        getVoteOptionsFieldBuilder() {
      if (voteOptionsBuilder_ == null) {
        voteOptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.kklab.vd.kumoi.proto.Vote.Option, com.kklab.vd.kumoi.proto.Vote.Option.Builder, com.kklab.vd.kumoi.proto.Vote.OptionOrBuilder>(
                voteOptions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        voteOptions_ = null;
      }
      return voteOptionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omega.VoteCount)
  }

  // @@protoc_insertion_point(class_scope:omega.VoteCount)
  private static final com.kklab.vd.kumoi.proto.VoteCount DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kklab.vd.kumoi.proto.VoteCount();
  }

  public static com.kklab.vd.kumoi.proto.VoteCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteCount>
      PARSER = new com.google.protobuf.AbstractParser<VoteCount>() {
    @java.lang.Override
    public VoteCount parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VoteCount(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VoteCount> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteCount> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kklab.vd.kumoi.proto.VoteCount getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

