// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface VoteOwnerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.VoteOwnerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The voteId.
   */
  java.lang.String getVoteId();
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The bytes for voteId.
   */
  com.google.protobuf.ByteString
      getVoteIdBytes();

  /**
   * <code>string message = 2[json_name = "m"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2[json_name = "m"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *  google.protobuf.Struct metadata = 10 [json_name = "mta"];
   *  Skill skill = 11 [json_name = "sk"];
   * </pre>
   *
   * <code>bool sequential = 8[json_name = "se"];</code>
   * @return The sequential.
   */
  boolean getSequential();
}
