// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface VoteSelectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.VoteSelect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The voteId.
   */
  java.lang.String getVoteId();
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The bytes for voteId.
   */
  com.google.protobuf.ByteString
      getVoteIdBytes();

  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2[json_name = "s"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string vote_option_id = 4[json_name = "vto"];</code>
   * @return The voteOptionId.
   */
  java.lang.String getVoteOptionId();
  /**
   * <code>string vote_option_id = 4[json_name = "vto"];</code>
   * @return The bytes for voteOptionId.
   */
  com.google.protobuf.ByteString
      getVoteOptionIdBytes();

  /**
   * <code>bool deny = 5[json_name = "de"];</code>
   * @return The deny.
   */
  boolean getDeny();
}
