// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omega.proto

package com.kklab.vd.kumoi.proto;

public interface VoteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omega.VoteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The voteId.
   */
  java.lang.String getVoteId();
  /**
   * <code>string vote_id = 1[json_name = "vt"];</code>
   * @return The bytes for voteId.
   */
  com.google.protobuf.ByteString
      getVoteIdBytes();

  /**
   * <code>string from_session = 2[json_name = "fs"];</code>
   * @return The fromSession.
   */
  java.lang.String getFromSession();
  /**
   * <code>string from_session = 2[json_name = "fs"];</code>
   * @return The bytes for fromSession.
   */
  com.google.protobuf.ByteString
      getFromSessionBytes();

  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3[json_name = "sub"];</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4[json_name = "m"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool sequential = 8[json_name = "se"];</code>
   * @return The sequential.
   */
  boolean getSequential();

  /**
   * <pre>
   *  google.protobuf.Struct metadata = 10 [json_name = "mta"];
   *  Skill skill = 11 [json_name = "sk"];
   * </pre>
   *
   * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
   * @return The enum numeric value on the wire for roleIndicator.
   */
  int getRoleIndicatorValue();
  /**
   * <pre>
   *  google.protobuf.Struct metadata = 10 [json_name = "mta"];
   *  Skill skill = 11 [json_name = "sk"];
   * </pre>
   *
   * <code>.omega.Role roleIndicator = 9[json_name = "ri"];</code>
   * @return The roleIndicator.
   */
  com.kklab.vd.kumoi.proto.Role getRoleIndicator();
}
